version: '3'
services:
  web:
    build: .
    ports:
    - "8080:8080"
    volumes:
      - ".:/build"
    environment:
      FLASK_ENV: development
  redist:
    image: "redis:alpine"
  db:
    image: postgres
    restart: always
    volumes:
      - "dbdata:/var/lib/postgresql/data"

volumes:
  dbdata: